application: apkuploader
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  login: required
- url: /c/.*
  script: main.py
  login: required
- url: .*
  script: download.py
